pkl_file_path: 'Data\Processed\Femur and Knee procedures_CPT_database_dataset_module.pickle'
ollama_model: 'mistral-nemo'
output_directory: 'Femur_and_Knee_positive_mistral_test_5_21'
sample_cpt_database: Data\CPT_Databases\Leg and Ankle procedures_CPT_database.json
sample_type: 'Positive'
sample_number: 1000
temperature: 0
ksearchvalue: 5
variables:
 type_of_orthopedic_surgery: 'Femur and Knee Procedures'
 length_of_overall_explanation: 33
