pkl_file_path: ''
ollama_model: 'mistral-nemo'
output_directory: 'Femur_and_Knee'
sample_cpt_database: 
sample_type: 'Positive'
sample_number: 1000
temperature: 0
ksearchvalue: 5
variables:
 type_of_orthopedic_surgery: 'Femur and Knee Procedures'
 length_of_overall_explanation: 33
